[package]
name = "demo-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "demo-client"
path = "src/main.rs"

[dependencies]
bicycle-protocol = { path = "../../crates/protocol" }
anyhow.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
