[package]
name = "bicycle-webui"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "webui"
path = "src/main.rs"

[dependencies]
bicycle-protocol = { path = "../../crates/protocol" }
bicycle-core = { path = "../../crates/core" }
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tonic.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
