[package]
name = "bicycle-protocol"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
serde.workspace = true

[build-dependencies]
tonic-build.workspace = true
protobuf-src.workspace = true
